### ISSUE TITLE
Instructions should reflect IDE-based workflow

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/html-css-personal-site-project-part-1#2]
At the outset, instead of forking and cloning the instruction should be to simply user the Open button. 

The instruction to branch seems unnecessary? Why not just have the user make their code changes in their cloned fork and submit it with `learn submit`?

**Comment by pletcher** [comment]
I think in this case, the Open button won't work, as it would just open up this lesson -- we want the students to create their own repos for `projectname.github.io` site publishing. (We don't want students fighting for `html-css-personal-site-project-part-1.github.io`, for example.)

Branching is also relevant here, as GitHub automagically uses `gh-pages` branches for publishing the site.

**Comment by matbalez-zz** [comment]
Gotcha. Thanks Chuck!

Closing.

**Comment by matbalez-zz** [comment]
Actually, I filed this issue on the wrong lab. Meant to file here: 
https://learn.co/tracks/building-responsive-websites-with-html-css/html-part-2/fundamentals/html-elements-code-along. Posting it there. Please consider in that context?
